[web]
  host = "0.0.0.0"
  port = 8080
  cert = ""
  key = ""
  Debug = true

[db]
  host = "10.20.30.144"
  port = 3306
  user = "db"
  passwd = "1c3c2d4572236897d2e9cc90b9643424"
  dbname = "vulnerability"
  db-type = "mysql"
  show-sql = false
  read-only = false
  max-idle-conn-count = 20
  max-open-conn-count = 100
  max-conn-life-time = 600

[iam]
 base_url = "http://iam.dev.yt-security.com:32000"
 client_id = "01KR3C53FQNJYRSH6AKCM7AK0K"
 client_secret = "sk-eb3d9b09f7537aa14f36e1ddd89c2575"
 path_prefix = "/api"

[sso]
  callback_uri = "http://localhost:8900/callback"
  success_redirect         = "http://localhost:5890/auth/sso-callback"
  cookie_secret            = "at-least-16-bytes-secret-key!!"
  token_relay_callback_uri = "http://localhost:8900/callback"
