[web]
  host = "0.0.0.0"
  port = 8080
  cert = ""
  key = ""
  Debug = true

[db]
  host = "10.20.30.144"
  port = 3306
  user = "db"
  passwd = "1c3c2d4572236897d2e9cc90b9643424"
  dbname = "vulnerability"
  db-type = "mysql"
  show-sql = false
  read-only = false
  max-idle-conn-count = 20
  max-open-conn-count = 100
  max-conn-life-time = 600

[iam]
  base_url = "http://iam.dev.yt-security.com:32000"
  client_id = "01KSM36602167DKAAAJE6RM2AD"
  client_secret = "sk-de22bb8b2acbb2b1d9a0e1e40cd67fcd"
  path_prefix = "/api"

[sso]
  callback_uri = "http://warning-platform.dev.yt-security.com:32000/callback"
  success_redirect = "http://warning-platform.dev.yt-security.com:32000/auth/sso-callback"
  cookie_secret = "pp8v7vWsPgaeviINPd4Dio9fb$StZxML"
  token_relay_callback_uri = "http://warning-platform.dev.yt-security.com:32000/callback"
