USE traffic;
INSERT INTO events (event_id,event_name,title,message,context,source,severity,category,event_status,current_round,observables,created_at,updated_at,review_status,review_comment,reviewed_by,analysis_version,aggregation_closed,last_analysis_at,last_seen_at) VALUES
('demo-event-001','外网 SSH 暴力破解','检测到 SSH 暴力破解活动','来自多个外部地址的 SSH 登录失败次数异常升高','{"event_type":"brute_force","src_ip":"203.0.113.45","dst_ip":"10.20.1.10","protocol":"ssh","occurrence_count":128,"first_time":"2026-09-14T08:20:00Z","last_time":"2026-09-14T08:35:00Z","duration":900,"flow_stats":{"total_packets":128,"total_wire_bytes":74240},"detection_method":"规则检测"}','sensor-demo','high','access_attack','pending',1,'[{"type":"ip","value":"203.0.113.45","role":"source"},{"type":"ip","value":"10.20.1.10","role":"target"}]',NOW()-INTERVAL 2 HOUR,NOW()-INTERVAL 90 MINUTE,'pending','','',1,1,NOW()-INTERVAL 80 MINUTE,NOW()-INTERVAL 90 MINUTE),
('demo-event-002','可疑 WebShell 文件','Web 服务器发现可疑脚本文件','在应用服务器上传目录发现疑似 WebShell 文件','{"event_type":"webshell","src_ip":"198.51.100.24","dst_ip":"10.20.1.20","protocol":"http","occurrence_count":3,"first_time":"2026-09-14T10:10:00Z","last_time":"2026-09-14T10:12:00Z","duration":120,"detection_method":"文件监控"}','sensor-demo','critical','web_attack','investigating',2,'[{"type":"ip","value":"198.51.100.24","role":"source"},{"type":"ip","value":"10.20.1.20","role":"target"}]',NOW()-INTERVAL 50 MINUTE,NOW()-INTERVAL 35 MINUTE,'pending','','',2,0,NOW()-INTERVAL 30 MINUTE,NOW()-INTERVAL 35 MINUTE),
('demo-event-003','DNS 隧道通信','发现疑似 DNS 隧道流量','内部终端持续请求高熵子域名，疑似数据外传','{"event_type":"dns_tunnel","src_ip":"10.20.2.15","dst_ip":"8.8.8.8","protocol":"dns","occurrence_count":57,"first_time":"2026-09-14T11:00:00Z","last_time":"2026-09-14T11:25:00Z","duration":1500,"detection_method":"流量分析"}','sensor-demo','medium','data_exfiltration','resolved',1,'[{"type":"ip","value":"10.20.2.15","role":"source"},{"type":"ip","value":"8.8.8.8","role":"target"}]',NOW()-INTERVAL 20 MINUTE,NOW()-INTERVAL 10 MINUTE,'approved','已完成隔离与复核','demo-analyst',2,1,NOW()-INTERVAL 8 MINUTE,NOW()-INTERVAL 10 MINUTE)
ON DUPLICATE KEY UPDATE updated_at=VALUES(updated_at);
INSERT INTO messages (message_id,event_id,user_id,user_nickname,message_from,message_type,message_category,sender_type,chat_session_id,message_content,round_id) VALUES ('demo-msg-001','demo-event-001','demo-analyst','演示分析员','user','user_message','engineer_chat','user','demo-session-001','请分析此次 SSH 暴力破解的来源、目标和处置建议。',1),('demo-msg-002','demo-event-001','','分析引擎','assistant','analysis','agent','ai','demo-session-001','已确认来源地址存在高频失败登录行为，建议临时封禁来源 IP 并检查目标主机账号安全策略。',1),('demo-msg-003','demo-event-002','','分析引擎','assistant','analysis','agent','ai','demo-session-002','检测到疑似 WebShell 文件，建议立即隔离文件、保留样本并检查上传接口权限。',2) ON DUPLICATE KEY UPDATE message_content=VALUES(message_content);
INSERT INTO tasks (task_id,event_id,task_name,task_type,task_description,task_status,task_priority,assigned_to,task_assignee,round_id) VALUES ('demo-task-001','demo-event-001','核查 SSH 登录日志','investigation','核对来源 IP、登录失败次数及受影响账号','completed','high','demo-analyst','分析员',1),('demo-task-002','demo-event-002','隔离可疑 WebShell','containment','隔离样本并阻断相关上传路径','in_progress','critical','demo-analyst','分析员',2),('demo-task-003','demo-event-003','检查 DNS 请求终端','investigation','确认终端进程与 DNS 请求内容','completed','medium','demo-analyst','分析员',1) ON DUPLICATE KEY UPDATE task_status=VALUES(task_status),updated_at=NOW();
INSERT INTO actions (action_id,task_id,event_id,round_id,action_name,action_type,action_assignee,action_status,action_result) VALUES ('demo-action-001','demo-task-001','demo-event-001',1,'封禁来源 IP','block_ip','分析员','completed','已加入临时阻断列表'),('demo-action-002','demo-task-002','demo-event-002',2,'隔离样本文件','isolate_file','分析员','in_progress','等待人工确认样本路径'),('demo-action-003','demo-task-003','demo-event-003',1,'终端隔离检查','endpoint_check','分析员','completed','未发现持续外联进程') ON DUPLICATE KEY UPDATE action_status=VALUES(action_status),updated_at=NOW();
INSERT INTO summaries (event_id,round_id,event_summary,version,kind) VALUES ('demo-event-001',1,'该事件表现为来自 203.0.113.45 的 SSH 暴力破解，目标为 10.20.1.10，共观测到 128 次失败登录。建议封禁来源、检查账号策略并开启多因素认证。',1,'initial'),('demo-event-002',2,'在 Web 服务器上传目录发现疑似 WebShell 文件，事件处于调查中，建议先隔离文件并保留取证信息。',2,'final'),('demo-event-003',1,'检测到内部终端向公共 DNS 解析器发起高频高熵请求，已完成终端检查，暂未发现持续外联进程。',2,'final') ON DUPLICATE KEY UPDATE event_summary=VALUES(event_summary),updated_at=NOW();
INSERT INTO traffic_assets (id,name,asset_type,address,unit,owner,status,remark) VALUES ('demo-asset-001','核心 Web 服务器','server','10.20.1.20','研发中心','平台组',1,'演示资产'),('demo-asset-002','办公终端-015','endpoint','10.20.2.15','办公网','终端用户',1,'演示资产'),('demo-asset-003','SSH 服务器','server','10.20.1.10','生产环境','运维组',1,'演示资产') ON DUPLICATE KEY UPDATE updated_at=NOW();
