package dict

func builtinSubdomains() []string {
	return []string{
		"www", "mail", "ftp", "smtp", "pop", "pop3", "imap", "dns", "ns", "ns1", "ns2", "ns3", "ns4",
		"mx", "mx1", "mx2", "relay", "vpn", "remote", "gateway", "gw", "proxy",
		"api", "api1", "api2", "api-gateway", "apis", "rest", "graphql", "grpc",
		"dev", "develop", "development", "staging", "stage", "stg", "qa", "test", "testing", "uat",
		"pre", "preprod", "pre-prod", "beta", "alpha", "canary", "nightly", "sandbox",
		"prod", "production", "live", "app", "apps", "application",
		"admin", "administrator", "manage", "management", "console", "dashboard", "panel",
		"portal", "login", "auth", "sso", "cas", "oauth", "oauth2", "idp", "identity",
		"web", "www1", "www2", "web1", "web2", "site", "sites", "home", "homepage",
		"blog", "cms", "wp", "wordpress", "drupal", "joomla",
		"shop", "store", "cart", "pay", "payment", "checkout", "order", "orders",
		"static", "assets", "img", "images", "image", "media", "cdn", "cdn1", "cdn2",
		"css", "js", "files", "file", "upload", "uploads", "download", "downloads",
		"git", "svn", "repo", "repository", "code", "source", "src",
		"ci", "cd", "jenkins", "gitlab", "github", "bitbucket", "drone", "travis", "actions",
		"db", "database", "mysql", "postgres", "pgsql", "redis", "mongo", "mongodb", "elastic", "elasticsearch",
		"mq", "rabbitmq", "kafka", "activemq", "nats", "queue", "amqp",
		"cache", "memcached", "varnish",
		"log", "logs", "logging", "syslog", "elk", "kibana", "grafana", "prometheus", "monitor", "monitoring",
		"metrics", "apm", "trace", "tracing", "jaeger", "zipkin",
		"doc", "docs", "documentation", "help", "support", "wiki", "kb", "knowledge",
		"chat", "im", "message", "msg", "notify", "notification", "push",
		"search", "solr", "lucene",
		"report", "reports", "analytics", "bi", "data", "bigdata", "hadoop", "spark",
		"ml", "ai", "model", "models", "inference",
		"k8s", "kube", "kubernetes", "docker", "container", "registry", "harbor",
		"cloud", "aws", "azure", "gcp", "aliyun", "alicloud", "tencent",
		"oss", "s3", "storage", "minio", "ceph",
		"backup", "bak", "archive",
		"internal", "intranet", "corp", "corporate", "office",
		"crm", "erp", "hr", "oa", "iam", "ldap", "ad",
		"ticket", "jira", "confluence", "redmine", "zentao",
		"forum", "bbs", "community",
		"video", "stream", "live", "rtmp", "rtsp",
		"map", "maps", "geo", "location",
		"wap", "m", "mobile", "touch",
		"api-doc", "api-docs", "swagger", "openapi",
		"health", "healthcheck", "status", "info", "version",
		"demo", "example", "sample",
		"new", "old", "legacy", "v2", "v3",
		"en", "cn", "zh", "us", "eu",
		"node", "node1", "node2", "node3", "worker", "worker1", "worker2",
		"master", "slave", "primary", "secondary",
		"lb", "loadbalancer", "haproxy", "nginx", "traefik", "envoy",
		"sec", "security", "waf", "firewall", "ids", "ips",
		"scan", "scanner", "audit", "siem",
		"zabbix", "nagios", "cacti", "prtg",
		"ntp", "time", "cron", "scheduler",
		"config", "conf", "settings", "env",
		"update", "updates", "patch",
		"relay1", "relay2", "outbound", "inbound",
		"edge", "edge1", "edge2", "pop", "pop1",
		"server", "server1", "server2", "host", "host1", "host2",
		"mx01", "mx02", "smtp01", "smtp02",
		"vpn1", "vpn2", "openvpn", "wireguard",
		"jump", "jumpserver", "bastion",
		"ansible", "puppet", "chef", "terraform", "vault",
		"consul", "etcd", "zookeeper",
		"webmail", "email", "exchange",
		"iot", "mqtt", "device", "devices",
		"print", "printer", "scan",
		"park", "parking", "redirect",
	}
}

func builtinDirpaths() []string {
	return []string{
		".git/HEAD", ".git/config", ".git/index", ".gitignore",
		".svn/entries", ".svn/wc.db",
		".env", ".env.local", ".env.production", ".env.development", ".env.backup", ".env.bak",
		".DS_Store", ".htaccess", ".htpasswd", ".npmrc", ".dockerignore",
		"robots.txt", "sitemap.xml", "crossdomain.xml", "security.txt", ".well-known/security.txt",
		"favicon.ico", "humans.txt",
		"web.config", "applicationContext.xml", "server.xml",
		"wp-config.php", "wp-config.php.bak", "config.php", "config.php.bak",
		"configuration.php", "database.yml", "settings.py",
		"admin", "admin/", "administrator/", "admin.php", "admin.html",
		"login", "login/", "login.php", "login.html", "signin", "signup",
		"register", "register/",
		"manager/", "console/", "dashboard/", "panel/", "cpanel/",
		"user/", "users/", "profile/", "account/",
		"wp-admin/", "wp-login.php", "wp-content/", "wp-includes/",
		"wp-json/", "wp-json/wp/v2/users",
		"phpmyadmin/", "pma/", "myadmin/", "phpMyAdmin/",
		"phpinfo.php", "info.php", "test.php", "pi.php",
		"adminer.php", "adminer/",
		"api/", "api/v1/", "api/v2/", "api/v3/",
		"api/swagger.json", "api/swagger.yaml", "api/openapi.json",
		"swagger/", "swagger-ui.html", "swagger-ui/", "swagger-resources",
		"api-docs", "api-docs/", "redoc",
		"graphql", "graphiql", "graphql/console",
		"actuator", "actuator/health", "actuator/env", "actuator/beans",
		"actuator/configprops", "actuator/mappings", "actuator/info",
		"actuator/metrics", "actuator/threaddump", "actuator/heapdump",
		"metrics", "health", "healthz", "readyz", "livez",
		"status", "server-status", "server-info",
		"debug/", "debug/pprof/", "debug/vars",
		"trace", "trace/", "_profiler",
		"backup/", "backup.zip", "backup.tar.gz", "backup.sql", "backup.bak",
		"database.sql", "dump.sql", "db.sql", "data.sql",
		"site.sql", "www.zip", "www.tar.gz", "wwwroot.zip",
		".idea/", ".vscode/", "node_modules/",
		"vendor/", "bower_components/",
		"test/", "tests/", "spec/", "specs/",
		"Dockerfile", "docker-compose.yml", "docker-compose.yaml",
		"Vagrantfile", "Jenkinsfile", "Procfile",
		"package.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
		"composer.json", "composer.lock",
		"Gemfile", "Gemfile.lock",
		"requirements.txt", "Pipfile", "setup.py",
		"go.mod", "go.sum", "Cargo.toml",
		"pom.xml", "build.gradle", "build.sbt",
		"Makefile", "CMakeLists.txt",
		"readme.md", "README.md", "CHANGELOG.md", "TODO.md",
		"LICENSE", "LICENSE.txt", "NOTICE",
		"error", "errors", "404.html", "500.html",
		"static/", "assets/", "public/", "resources/",
		"uploads/", "upload/", "files/", "media/",
		"images/", "img/", "css/", "js/",
		"temp/", "tmp/", "cache/", "log/", "logs/",
		"cgi-bin/", "scripts/", "includes/",
		"install/", "install.php", "setup/", "setup.php",
		"xmlrpc.php", "wp-cron.php",
		"solr/", "solr/admin/", "elasticsearch/",
		"kibana/", "grafana/", "prometheus/",
		"jenkins/", "bamboo/", "teamcity/",
		"nexus/", "artifactory/",
		"nacos/", "consul/", "eureka/",
		"druid/", "druid/index.html",
		"dubbo/", "zookeeper/",
	}
}

func builtinUsernames() []string {
	return []string{
		"admin", "administrator", "root", "test", "user", "guest",
		"demo", "operator", "manager", "master", "super", "sysadmin",
		"system", "service", "support", "helpdesk",
		"ftp", "ftpuser", "anonymous",
		"webmaster", "www", "web",
		"postgres", "mysql", "oracle", "mssql", "sa", "dba",
		"redis", "mongo", "mongodb", "elastic", "elasticsearch",
		"tomcat", "jboss", "weblogic", "websphere",
		"jenkins", "git", "svn",
		"deploy", "release", "ci", "cd",
		"backup", "monitor", "nagios", "zabbix",
		"info", "debug", "dev", "developer",
		"api", "app", "application",
		"mail", "email", "postmaster",
		"nobody", "daemon", "bin",
		"ubuntu", "centos", "ec2-user", "core", "vagrant",
		"docker", "kubernetes", "k8s",
		"www-data", "apache", "nginx", "httpd",
		"admin1", "admin123", "test123", "user1",
		"superadmin", "siteadmin", "netadmin",
	}
}

func builtinPasswords() []string {
	return []string{
		"admin", "admin123", "admin@123", "admin888", "admin666", "admin!@#",
		"123456", "1234567", "12345678", "123456789", "1234567890",
		"password", "password1", "password123", "passw0rd", "P@ssw0rd",
		"root", "root123", "root@123", "toor",
		"test", "test123", "test@123", "testing",
		"guest", "guest123",
		"default", "changeme", "letmein", "welcome", "monkey",
		"qwerty", "qwerty123", "abc123", "111111", "000000", "666666", "888888",
		"master", "dragon", "login",
		"shadow", "sunshine", "trustno1",
		"iloveyou", "princess", "football",
		"123123", "654321", "121212", "159753",
		"!@#$%^", "!@#$%^&*",
		"Aa123456", "Aa123456!", "Qwer1234", "Qwer1234!",
		"P@ss1234", "Pass1234", "Pa$$w0rd",
		"Admin@123", "Root@123", "Test@123",
		"a123456", "a12345678",
		"1qaz2wsx", "1qaz@WSX", "1q2w3e4r",
		"zxcvbnm", "asdfghjk", "qwertyuiop",
		"abcd1234", "abcd@1234",
		"system", "manager", "secret",
		"sa", "sa123", "sa@123",
		"postgres", "postgres123",
		"mysql", "mysql123",
		"redis", "redis123",
		"oracle", "oracle123",
		"tomcat", "tomcat123",
		"weblogic", "weblogic1",
		"jenkins", "jenkins123",
	}
}
