export const stageLabels: Record<string, string> = {
  discover: '资产发现',
  recon: '信息收集',
  vuln: '漏洞检测',
  exploit: '漏洞利用',
  report: '报告生成',
};

export const dataKeyLabels: Record<string, string> = {
  url: 'URL',
  ip: 'IP',
  port: '端口',
  protocol: '协议',
  host: '主机',
  domain: '域名',
  service: '服务',
  version: '版本',
  banner: 'Banner',
  server: '服务器',
  powered_by: '技术栈',
  status_code: '状态码',
  title: '页面标题',
  name: '名称',
  category: '分类',
  method: '方法',
  record_type: '记录类型',
  value: '值',
  hash: 'Hash',
  username: '用户名',
  password: '密码',
  param: '参数',
  payload: 'Payload',
  type: '攻击类型',
  context: '上下文',
  cipher_suite: '密码套件',
  algorithm: '算法',
  key_size: '密钥大小',
  common_name: 'CN',
  issuer: '签发者',
  expired_at: '过期时间',
  expires_at: '到期时间',
  tls_version: 'TLS版本',
  waf: 'WAF',
  api_type: 'API类型',
  status: '状态',
  path: '路径',
  action: '表单Action',
  inputs: '输入字段',
  parameters: '参数',
  enctype: '编码类型',
  email: '邮箱',
  source: '来源',
  confidence_basis: '置信度依据',
  matched_seed: '命中种子域',
  matched_seed_root: '命中根域',
  matched_company: '命中公司名',
  query_company: '查询企业名称',
  matched_host: '搜索结果主机',
  tag: '标签',
  attribute: '属性',
  technologies: '技术栈',
  content_length: '内容长度',
  cdn_name: 'CDN',
  is_cdn: 'CDN检测',
  subdomain: '子域名',
  internal_ips: '内网IP',
  record_count: '记录数',
  scheme: '协议',
  response_time: '响应时间',
  redirect_url: '跳转地址',
  favicon_hash: 'Favicon Hash',
  jarm_hash: 'JARM Hash',
  content_type: '内容类型',
  header_server: '服务器',
  screenshot: '页面截图',
};

export const typeLabels: Record<string, string> = {
  host_alive: '主机存活',
  port_open: 'TCP端口',
  udp_port: 'UDP端口',
  service: '服务识别',
  web_page: '网页',
  web_info: '网页',
  url: 'URL发现',
  form: '表单',
  script: '脚本',
  crawler: '爬虫发现',
  xhr: 'XHR请求',
  dns_record: 'DNS记录',
  subdomain: '子域名',
  dns_cname: 'DNS CNAME',
  dns_multi_ip: 'DNS多IP',
  dns_nameservers: 'DNS服务器',
  reverse_dns: '反向DNS',
  zone_transfer: '域传送',
  cert_info: '证书信息',
  cert_expired: '证书过期',
  cert_expiring_soon: '证书即将过期',
  self_signed_cert: '自签名证书',
  weak_tls: 'TLS弱配置',
  tls_fingerprint: 'TLS指纹',
  tls_cert_expired: 'TLS证书过期',
  tls_weak_version: 'TLS弱版本',
  weak_cipher: '弱加密套件',
  weak_signature: '弱签名算法',
  weak_key: '弱密钥',
  tech: '技术栈',
  tech_stack: '技术栈',
  fingerprint: '指纹',
  favicon: 'Favicon',
  favicon_hash: 'Favicon Hash',
  header_fingerprint: 'HTTP头指纹',
  js_fingerprint: 'JS指纹',
  screenshot: '页面截图',
  waf: 'WAF检测',
  waf_detected: 'WAF检测',
  cdn_detected: 'CDN检测',
  load_balancer_detected: '负载均衡',
  traceroute: '路由追踪',
  network_gateway: '网络网关',
  ip_attribution: 'IP归属',
  real_ip: '真实IP',
  asn: 'ASN信息',
  organization: '组织信息',
  domain: '域名信息',
  ip_range: 'IP段',
  internal_ip_leak: '内网IP泄露',
  email: '邮箱',
  api_endpoint: 'API端点',
  directory: '目录',
  missing_security_headers: '缺失安全头',
  code_leak: '代码泄露',
  cyber_asset: '网络资产',
  nuclei: 'Nuclei检测',
  info_leak: '信息泄露',
  body_regex: '正则匹配',
  body_contains: '内容匹配',
  header: 'HTTP头',
  git_leak: 'Git泄露',
  dir_found: '目录发现',
  sqli: 'SQL注入',
  sqli_error: 'SQLi(错误)',
  sqli_boolean: 'SQLi(布尔)',
  sqli_time: 'SQLi(时间)',
  sqli_union: 'SQLi(联合)',
  xss: 'XSS',
  xss_reflected: 'XSS(反射)',
  xss_dom: 'XSS(DOM)',
  ssrf: 'SSRF',
  ssrf_potential: 'SSRF(疑似)',
  cmdi_time: '命令注入(时间)',
  cmdi_output: '命令注入(回显)',
  lfi: '文件包含',
  ssti: 'SSTI',
  ssti_error: 'SSTI(错误)',
  ssti_exploit: 'SSTI(利用)',
  xxe_error: 'XXE(错误)',
  xxe_entity: 'XXE(实体)',
  xxe_file_read: 'XXE(文件读取)',
  xxe_ssrf: 'XXE(SSRF)',
  nosqli_error: 'NoSQLi(错误)',
  nosqli_boolean: 'NoSQLi(布尔)',
  nosqli_operator: 'NoSQLi(运算符)',
  nosqli_auth_bypass: 'NoSQLi(认证绕过)',
  jwt_alg_none: 'JWT(alg:none)',
  jwt_no_expiry: 'JWT(无过期)',
  jwt_long_expiry: 'JWT(长过期)',
  jwt_weak_secret: 'JWT(弱密钥)',
  jwt_alg_none_bypass: 'JWT(none绕过)',
  jwt_empty_sig: 'JWT(空签名)',
  weak_pass: '弱口令',
  weak_password: '弱口令',
  api_endpoint_exposed: 'API暴露',
  api_unauth_access: 'API未授权',
  api_no_rate_limit: 'API无限流',
  api_info_leak_header: 'API头泄露',
  api_cors_wildcard: 'CORS通配',
  api_verbose_error: 'API详细错误',
  api_idor: 'IDOR',
  api_graphql_introspection: 'GraphQL自省',
  api_graphql_types: 'GraphQL类型',
};

export const typeColors: Record<string, string> = {
  host_alive: '#38a169',
  port_open: '#3182ce', udp_port: '#2b6cb0',
  service: '#805ad5',
  web_page: '#dd6b20', web_info: '#dd6b20', url: '#718096', form: '#d69e2e', script: '#805ad5', xhr: '#805ad5', crawler: '#718096',
  dns_record: '#d69e2e', subdomain: '#319795',
  dns_cname: '#d69e2e', dns_multi_ip: '#d69e2e', dns_nameservers: '#d69e2e', reverse_dns: '#d69e2e', zone_transfer: '#e53e3e',
  cert_info: '#e53e3e', cert_expired: '#e53e3e', cert_expiring_soon: '#ed8936', self_signed_cert: '#e53e3e',
  weak_tls: '#c53030', tls_fingerprint: '#805ad5', tls_cert_expired: '#e53e3e', tls_weak_version: '#c53030',
  weak_cipher: '#c53030', weak_signature: '#c53030', weak_key: '#c53030',
  tech: '#9f7aea', tech_stack: '#9f7aea', fingerprint: '#9f7aea', favicon: '#805ad5', favicon_hash: '#805ad5',
  header_fingerprint: '#9f7aea', js_fingerprint: '#667eea', screenshot: '#a0aec0',
  waf: '#fc8181', waf_detected: '#fc8181',
  cdn_detected: '#38b2ac', load_balancer_detected: '#38b2ac',
  traceroute: '#2b6cb0', network_gateway: '#805ad5',
  ip_attribution: '#4a5568', real_ip: '#2d3748', asn: '#4a5568', organization: '#4a5568', domain: '#4a5568', ip_range: '#4a5568',
  internal_ip_leak: '#ed8936',
  email: '#667eea', api_endpoint: '#3182ce', directory: '#718096',
  missing_security_headers: '#ed8936', code_leak: '#c53030', cyber_asset: '#4a5568', nuclei: '#e53e3e',
  info_leak: '#ecc94b', body_regex: '#ecc94b', body_contains: '#ecc94b', header: '#718096',
  git_leak: '#c53030', dir_found: '#718096',
  sqli: '#e53e3e', sqli_error: '#e53e3e', sqli_boolean: '#e53e3e', sqli_time: '#e53e3e', sqli_union: '#e53e3e',
  xss: '#ed8936', xss_reflected: '#ed8936', xss_dom: '#ed8936',
  ssrf: '#e53e3e', ssrf_potential: '#fc8181',
  cmdi_time: '#c53030', cmdi_output: '#c53030',
  lfi: '#e53e3e',
  ssti: '#d53f8c', ssti_error: '#d53f8c', ssti_exploit: '#c53030',
  xxe_error: '#9b2c2c', xxe_entity: '#9b2c2c', xxe_file_read: '#9b2c2c', xxe_ssrf: '#9b2c2c',
  nosqli_error: '#b83280', nosqli_boolean: '#b83280', nosqli_operator: '#b83280', nosqli_auth_bypass: '#c53030',
  jwt_alg_none: '#805ad5', jwt_no_expiry: '#805ad5', jwt_long_expiry: '#805ad5', jwt_weak_secret: '#c53030', jwt_alg_none_bypass: '#c53030', jwt_empty_sig: '#c53030',
  weak_pass: '#ed8936', weak_password: '#ed8936',
  api_endpoint_exposed: '#e53e3e', api_unauth_access: '#c53030', api_no_rate_limit: '#ed8936',
  api_info_leak_header: '#ecc94b', api_cors_wildcard: '#e53e3e', api_verbose_error: '#ed8936',
  api_idor: '#c53030', api_graphql_introspection: '#805ad5', api_graphql_types: '#805ad5',
  vuln: '#e53e3e', infra: '#4a5568', api_disc: '#3182ce', info_collect: '#667eea',
};

export const moduleLabels: Record<string, string> = {
  host_discover: '主机发现',
  web_recon: 'Web 信息收集',
  asset_enrich: '资产富化',
  web_vuln_scan: 'Web 漏洞检测',
  credential_audit: '凭据安全',
  infra_extra: '网络拓扑',
  icmp_ping: 'ICMP存活探测',
  port_scan: '端口扫描',
  syn_scan: 'SYN扫描',
  udp_scan: 'UDP扫描',
  service_probe: '服务识别',
  web_crawl: '网站爬虫',
  subdomain_brute: '子域名枚举',
  dns_all: 'DNS全量查询',
  tech_detect: '技术栈识别',
  waf_detect: 'WAF检测',
  web_fingerprint: '指纹识别',
  cert_check: '证书安全检查',
  favicon: '图标哈希识别',
  js_analyze: 'JS敏感信息分析',
  api_disc: 'API接口发现',
  dir_scan: '目录扫描',
  real_ip: '真实IP探测',
  ip_attr: 'IP属性查询',
  email_collect: '邮箱收集',
  company_recon: '企业资产发现',
  fpenhance: '增强指纹探测',
  nettopo: '网络拓扑探测',
  cyberspace: '网络空间测绘',
  sqli: 'SQL注入检测',
  xss: 'XSS检测',
  ssrf: 'SSRF检测',
  cmdi: '命令注入检测',
  lfi: '文件包含检测',
  ssti: '模板注入检测',
  xxe: 'XXE注入检测',
  nosqli: 'NoSQL注入检测',
  jwt_sec: 'JWT安全检测',
  weak_pass: '弱口令检测',
  brute_force: '密码爆破',
  info_leak: '信息泄露检测',
  git_leak: 'Git仓库泄露',
  apisec: 'API安全检测',
  screenshot: '页面截图',
  nuclei: 'Nuclei PoC',
  'nuclei-poc': 'Nuclei PoC',
  advanced_vuln: '高级漏洞检测',
  unauth: '未授权访问检测',
};

export const profileLabels: Record<string, string> = {
  full: '全面扫描',
  quick: '快速扫描',
  recon: '信息收集',
  vuln: '漏洞扫描',
  'vuln-full': '深度漏洞',
};

export const severityConfig: Record<string, { color: string; label: string }> = {
  critical: { color: '#e53e3e', label: '严重' },
  high: { color: '#ed8936', label: '高危' },
  medium: { color: '#ecc94b', label: '中危' },
  low: { color: '#48bb78', label: '低危' },
  info: { color: '#4299e1', label: '信息' },
};

export const TYPES_IN_PORT_SERVICE_TAB = ['port_open', 'udp_port', 'service'] as const;
export const EXCLUDE_FROM_ALL_TAB = ['host_alive', ...TYPES_IN_PORT_SERVICE_TAB].join(',');

export const subTabDefs = [
  { key: 'overview', label: '任务概览', isOverview: true, group: 'summary' },
  { key: 'all', label: '全部', group: 'summary' },
  {
    key: 'port_open',
    label: '开放端口/服务',
    mergeTypes: [...TYPES_IN_PORT_SERVICE_TAB],
    group: 'summary',
  },
  { key: 'vuln', label: '漏洞', group: 'summary' },
  { key: 'host_alive', label: '存活主机', group: 'findings' },
  { key: 'subdomain', label: '子域名', group: 'findings' },
  { key: 'dns_record', label: 'DNS', mergeTypes: ['dns_record', 'dns_cname', 'dns_multi_ip', 'dns_nameservers', 'reverse_dns', 'zone_transfer'], group: 'findings' },
  { key: 'web_page', label: '网站/URL', mergeTypes: ['web_page', 'web_info', 'url', 'script', 'screenshot'], group: 'findings' },
  { key: 'crawler', label: '爬虫', mergeTypes: ['crawler', 'xhr'], group: 'findings' },
  { key: 'tech', label: '指纹', mergeTypes: ['tech', 'tech_stack', 'fingerprint', 'favicon', 'favicon_hash', 'header_fingerprint', 'js_fingerprint'], group: 'findings' },
  { key: 'cert_info', label: '证书/TLS', mergeTypes: ['cert_info', 'cert_expired', 'cert_expiring_soon', 'self_signed_cert', 'weak_tls', 'tls_fingerprint', 'tls_cert_expired', 'tls_weak_version', 'weak_cipher', 'weak_signature', 'weak_key'], group: 'findings' },
  { key: 'waf', label: 'WAF', mergeTypes: ['waf', 'waf_detected'], group: 'findings' },
  { key: 'infra', label: '基础设施', mergeTypes: ['ip_attribution', 'real_ip', 'asn', 'organization', 'domain', 'ip_range', 'internal_ip_leak'], group: 'findings' },
  { key: 'nettopo', label: '网络拓扑', mergeTypes: ['traceroute', 'network_gateway', 'dns_multi_ip', 'dns_cname', 'dns_nameservers', 'reverse_dns', 'cdn_detected', 'load_balancer_detected'], group: 'findings' },
  { key: 'form', label: '表单', group: 'findings' },
  { key: 'api_disc', label: 'API', mergeTypes: ['api_endpoint', 'api_endpoint_exposed', 'api_unauth_access', 'api_no_rate_limit', 'api_info_leak_header', 'api_cors_wildcard', 'api_verbose_error', 'api_idor', 'api_graphql_introspection', 'api_graphql_types'], group: 'findings' },
  { key: 'info_collect', label: '信息收集', mergeTypes: ['email', 'directory', 'dir_found', 'code_leak', 'cyber_asset', 'missing_security_headers', 'info_leak', 'body_regex', 'body_contains', 'header', 'git_leak', 'nuclei'], group: 'findings' },
] as const;

export type SubTabKey = (typeof subTabDefs)[number]['key'];

export const sourceLabels: Record<string, string> = {
  brute_pipeline: '字典爆破', brute_permutation: '排列爆破', brute_recursive: '递归爆破', brute: '暴力枚举',
  passive_crtsh: 'CRT.sh', 'crt.sh': 'CRT.sh', passive_wayback: 'Wayback', passive_otx: 'OTX',
  passive_rapiddns: 'RapidDNS', passive_hackertarget: 'HackerTarget',
  passive_threatcrowd: 'ThreatCrowd', passive_virustotal: 'VirusTotal',
  zone_transfer: '域传送', dns_transfer: '域传送', wildcard: '泛解析检测', tls_cert: 'TLS证书',
  crawler: '爬虫', html_parse: 'HTML解析', regex: '正则提取',
  bing_search: 'Bing搜索', github_search: 'GitHub搜索',
  dns_history: 'DNS历史', cdn_bypass: 'CDN绕过',
};

export const wellKnownPorts: Record<number, string> = {
  21: 'FTP', 22: 'SSH', 23: 'Telnet', 25: 'SMTP', 53: 'DNS', 80: 'HTTP', 110: 'POP3',
  143: 'IMAP', 443: 'HTTPS', 445: 'SMB', 993: 'IMAPS', 995: 'POP3S', 1433: 'MSSQL',
  1521: 'Oracle', 2375: 'Docker', 3306: 'MySQL', 3389: 'RDP', 5432: 'PostgreSQL',
  5672: 'AMQP', 6379: 'Redis', 8080: 'HTTP-Alt', 8443: 'HTTPS-Alt', 9200: 'ES', 27017: 'MongoDB',
};

export const dnsTypeColors: Record<string, string> = {
  A: '#1890ff', AAAA: '#722ed1', CNAME: '#13c2c2', MX: '#eb2f96',
  NS: '#fa8c16', TXT: '#52c41a', SOA: '#faad14', SRV: '#2f54eb', PTR: '#fa541c',
};

export const hostOnlyTabs = new Set(['subdomain', 'dns_record', 'cert_info', 'port_open', 'infra', 'nettopo', 'info_collect', 'all']);

export function formatTime(raw?: string) {
  if (!raw) return '-';
  const d = new Date(raw);
  if (isNaN(d.getTime())) return raw;
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
}

export function cleanTarget(raw: string): string {
  let t = raw;
  if (t.startsWith('http://')) t = t.slice(7);
  else if (t.startsWith('https://')) t = t.slice(8);
  t = t.replace(/\/+$/, '');
  const portMatch = t.match(/:(\d+)$/);
  if (portMatch) t = t.slice(0, -portMatch[0].length);
  return t;
}

export function getConfColor(conf: number): string {
  if (conf >= 90) return '#52c41a';
  if (conf >= 70) return '#faad14';
  if (conf >= 50) return '#fa8c16';
  return '#f5222d';
}

export function confLabel(conf: number): string {
  if (conf >= 90) return '高';
  if (conf >= 70) return '中高';
  if (conf >= 50) return '中';
  return '低';
}
